### ISSUE TITLE
一些使用建议

### ISSUE THREAD

**Issue by larrykoo711** [T-baby/MongoDB-Plugin#15]
#### 请酌情采纳 @T-baby
1. 建议删除validation验证相关代码，具体项目中不会在DB操作层去做强验证，MVC里面，验证在最上层的Controller层会处理，多次处理容易导致误解和增加业务复杂度；也更加单纯，减少几个依赖。
2. MongoKit是static的，建议更改成单例，或者采用enum方式实现单例，毕竟是有数据库驱动连接池的，单例比较好；
3. MongoKit提供带参构造，可通过构造进行初始实例化，也更好的兼容类型Spring框架的AOP注入，JFinal一样可以继承之后通过构造进行初始化；
4. Test建议改用单元测试，只需要继承TestCase就行了

**Comment by T-baby** [comment]
1.DB层不会进行强制验证，必须在其它地方使用validation方法，建议搭配[ICEREST](http://icerest.cc)使用。比如在[ICEREST](http://icerest.cc)的拦截器中校验：

``` java
public class ContentValidator extends Validator {
    @Override
    public ValidResult validate(Params params, RouteMatch routeMatch) {

        ItemBean item = params.getObject(ItemBean.class);

        return new ValidResult().mongoValid(item, "content");
    }
}
```

2.已在dev分支实现，确保唯一。

3.待考虑。

4.已排期。

**Comment by larrykoo711** [comment]
问题2，更改为enum单例了，method上就不再需要static了哦。

比较看好这类单纯的好工具，希望一期开发，我会贡献我的pullRequests

**Comment by T-baby** [comment]
恩恩，欢迎。建议经常关注[dev](https://github.com/T-baby/MongoDB-Plugin/tree/dev)分支，基本上更新都会发到这个分支。
