### ISSUE TITLE
新增的findOne返回Id处理有问题

### ISSUE THREAD

**Issue by larrykoo711** [T-baby/MongoDB-Plugin#16]
findOne返回的字段名为id，但是是一个将ObjectId转成String的字符串

**Comment by T-baby** [comment]
这个问题已经在 [dev](https://github.com/T-baby/MongoDB-Plugin/tree/dev) 分支中修复，为了解决https://github.com/T-baby/MongoDB-Plugin/issues/14 这个问题，选择了用fastjson来代替bson自身的转换，所以会把_id中所有信息带出来，而fastjson本身不支持下划线开头的key，所以现在在转换成json时，objectId会转为文本放入"id"中，并且会删除掉"_id"。
